version: "3"

services:
  app:
    container_name: "ruby-on-rails-prod-bookme"
    entrypoint: "dockerize -wait tcp://db:5432 .docker/entrypoints/prod.sh"
    build:
      context: .
      dockerfile: Dockerfile.prod
    depends_on:
      - db
    ports:
      - "3000:3000"
    networks:
      - rails
    volumes:
      - .:/var/www/bookme
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    build: .docker/postgres
    container_name: database-rails-prod-bookme
    volumes:
      - ./.docker/dbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
    env_file:
      - ./.env
    networks:
      - rails

networks:
  rails:
    driver: bridge
